ALTER TABLE offers ADD COLUMN
company_id INT NOT NULL REFERENCES companies(id)
ON DELETE SET NULL
ON UPDATE CASCADE;


ALTER TABLE experiences ADD COLUMN
student_id INT NOT NULL REFERENCES students(id)
ON DELETE SET NULL
ON UPDATE CASCADE;

